-- KPL — Supabase schema (run once in SQL Editor, or psql via DIRECT_URL).
--
-- Two tables:
--   auction_snapshot — the live auction state, one JSON row, pushed to screens.
--   players          — the roster (one row per player; edit here to add players).

-- ---------- Live auction snapshot (one JSON row) ----------
create table if not exists public.auction_snapshot (
  id         int primary key default 1,
  state      jsonb not null,
  updated_at timestamptz not null default now(),
  constraint single_row check (id = 1)
);

insert into public.auction_snapshot (id, state)
values (1, '{"version":0,"current":null,"teams":{},"players":{},"lastEvent":null}'::jsonb)
on conflict (id) do nothing;

alter table public.auction_snapshot enable row level security;
drop policy if exists "anon read snapshot" on public.auction_snapshot;
create policy "anon read snapshot"
  on public.auction_snapshot for select to anon, authenticated using (true);

-- ---------- Player roster ----------
create table if not exists public.players (
  id               text primary key,
  name             text not null,
  role             text not null
                     check (role in ('Batsman','Bowler','All-Rounder','Wicket Keeper')),
  batting_style    text not null default 'Right-hand bat',
  bowling_style    text,
  base_price       text not null default 'Base 2,000 LKR',
  base_price_value integer,
  status           text not null default 'Available For Auction',
  image            text,
  club             text,
  sort_order       integer not null default 0,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);

alter table public.players enable row level security;
drop policy if exists "anon read players" on public.players;
create policy "anon read players"
  on public.players for select to anon, authenticated using (true);

-- Push both tables' changes to subscribed browsers in real time.
do $$
begin
  begin
    alter publication supabase_realtime add table public.auction_snapshot;
  exception when duplicate_object then null;
  end;
  begin
    alter publication supabase_realtime add table public.players;
  exception when duplicate_object then null;
  end;
end $$;

-- ---------- Seed the real players so far ----------
insert into public.players
  (id, name, role, batting_style, bowling_style, base_price, base_price_value, status, image, club, sort_order)
values
  ('p-rijas','Rijas','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/rijas.jpg', 'Titans C.C', 0),
  ('p-asjaad','Asjaad','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/asjaad.jpg', 'Kins National', 1),
  ('p-waseem','Waseem','All-Rounder','Right-hand bat','Right-arm off-spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/waseem.jpg', 'Titans C.C', 2),
  ('p-feros','Feros','All-Rounder','Right-hand bat','Right-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/feros.jpg', 'Jamiya S.C', 3),
  ('p-fathi','Fathi','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/fathi.jpg', 'KCC', 4),
  ('p-suthais','Suthais','Wicket Keeper','Right-hand bat','Right-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/suthais.jpg', 'Upparu Kings S.C', 5),
  ('p-hafeez','Hafeez','Wicket Keeper','Right-hand bat','Right-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/hafeez.jpg', 'Upparu Kings S.C', 6),
  ('p-munsif','Munsif','All-Rounder','Left-hand bat','Left-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/munsif.jpg', 'Upparu Kings S.C', 7),
  ('p-rifath','Rifath','All-Rounder','Right-hand bat','Right-arm medium',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/rifath.jpg', 'Karachi Warriors S.C', 8),
  ('p-nowsar','Nowsar','All-Rounder','Right-hand bat','Right-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/nowsar.jpg', 'Karachi Warriors S.C', 9),
  ('p-saheer','Saheer','Batsman','Right-hand bat',null,
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/saheer.jpg', 'Karachi Warriors S.C', 10),
  ('p-javit','Javit','All-Rounder','Left-hand bat','Left-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/javit.jpg', 'Karachi Warriors S.C', 11),
  ('p-imran','Imran','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/imran.jpg', 'Golden Heroes S.C', 12),
  ('p-aathil','Aathil Ahamed','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/aathil.jpg', 'Golden Heroes S.C', 13),
  ('p-fairoos','Fairoos','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/fairoos.jpg', 'Golden Heroes S.C', 14),
  ('p-askar','Askar','Bowler','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/askar.jpg', 'Golden Heroes S.C', 15),
  ('p-ramees','Ramees','All-Rounder','Right-hand bat','Right-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/ramees.jpg', 'Golden Heroes S.C', 16),
  ('p-farees','Farees','All-Rounder','Right-hand bat','Right-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/farees.jpg', 'Golden Heroes S.C', 17),
  ('p-naseer','Naseer','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/naseer.jpg', 'Golden Heroes S.C', 18),
  ('p-akram','Akram','All-Rounder','Right-hand bat','Right-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/akram.jpg', 'Golden Heroes S.C', 19),
  ('p-rinos','Rinos','Batsman','Right-hand bat',null,
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/rinos.jpg', 'Noorany S.C', 20),
  ('p-munees','Munees','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/munees.jpg', 'Noorany S.C', 21),
  ('p-rifkhan','Rifkhan','Batsman','Right-hand bat',null,
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/rifkhan.jpg', 'Noorany S.C', 22),
  ('p-habeebullah','Habeebullah','Bowler','Right-hand bat','Right-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/habeebullah.jpg', 'Noorany S.C', 23),
  ('p-ilham','Ilham','Batsman','Left-hand bat',null,
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/ilham.jpg', 'Noorany S.C', 24),
  ('p-sifan','Sifan','All-Rounder','Right-hand bat','Right-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/sifan.jpg', 'Noorany S.C', 25),
  ('p-naheem','Naheem','All-Rounder','Right-hand bat','Right-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/naheem.jpg', 'Noorany S.C', 26),
  ('p-munas','Munas','All-Rounder','Right-hand bat','Right-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/munas.jpg', 'Noorany S.C', 27),
  ('p-rusthy','Rusthy','All-Rounder','Right-hand bat','Right-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/rusthy.jpg', 'Noorany S.C', 28),
  ('p-nowsath','Nowsath','Bowler','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/nowsath.jpg', 'Noorany S.C', 29),
  ('p-anas','Anas','Batsman','Right-hand bat',null,
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/anas.jpg', 'Noorany S.C', 30),
  ('p-ramsulla','Ramsulla','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/ramsulla.jpg', 'Hameediya S.C', 31),
  ('p-mufas','Mufas','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/mufas.jpg', 'Hameediya S.C', 32),
  ('p-arusulla','Arusulla','All-Rounder','Right-hand bat','Right-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/arusulla.jpg', 'Hameediya S.C', 33),
  ('p-rihan','Rihan','Wicket Keeper','Right-hand bat','Right-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/rihan.jpg', 'Hameediya S.C', 34),
  ('p-ijas-khan','Ijas Khan','Wicket Keeper','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/ijas-khan.jpg', 'Hameediya S.C', 35),
  ('p-sifan-h','Sifan','All-Rounder','Right-hand bat','Right-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/sifan-hameediya.jpg', 'Hameediya S.C', 36),
  ('p-fawsan','Fawsan','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/fawsan.jpg', 'An-Najah S.C', 37),
  ('p-saahir','Saahir','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/saahir.jpg', 'An-Najah S.C', 38),
  ('p-fahir','Fahir','Bowler','Right-hand bat','Right-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/fahir.jpg', 'An-Najah S.C', 39),
  ('p-nifras','Nifras','All-Rounder','Right-hand bat','Right-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/nifras.jpg', 'An-Najah S.C', 40),
  ('p-musnith','Musnith','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/musnith.jpg', 'An-Najah S.C', 41),
  ('p-sameer','Sameer','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/sameer.jpg', 'An-Najah S.C', 43),
  ('p-mashath-ali','Mashath Ali','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/mashath-ali.jpg', 'An-Najah S.C', 44),
  ('p-faseer','Faseer','All-Rounder','Right-hand bat','Right-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/faseer.jpg', 'An-Najah S.C', 45),
  ('p-sihath','Sihath','All-Rounder','Right-hand bat','Right-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/sihath.jpg', 'An-Najah S.C', 46),
  ('p-rimsan','Rimsan','Batsman','Right-hand bat',null,
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/rimsan.jpg', 'Al-Brooj S.C', 47),
  ('p-feros-ab','Feros','Bowler','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/feros-albrooj.jpg', 'Al-Brooj S.C', 48),
  ('p-niyas','Niyas','All-Rounder','Left-hand bat','Left-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/niyas.jpg', 'Al-Brooj S.C', 49),
  ('p-roshan','Roshan','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/roshan.jpg', 'Al-Brooj S.C', 50),
  ('p-safeer','Safeer','All-Rounder','Right-hand bat','Right-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/safeer.jpg', 'Al-Brooj S.C', 51),
  ('p-hazzan','Hazzan','All-Rounder','Right-hand bat','Right-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/hazzan.jpg', 'Al-Brooj S.C', 52),
  ('p-jabith','Jabith','Wicket Keeper','Right-hand bat','Right-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/jabith.jpg', 'Al-Brooj S.C', 53),
  ('p-waseem-ab','Waseem','All-Rounder','Right-hand bat','Right-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/waseem-albrooj.jpg', 'Al-Brooj S.C', 54),
  ('p-sanoor','Sanoor','All-Rounder','Right-hand bat','Right-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/sanoor.jpg', 'Al-Brooj S.C', 55),
  ('p-nifras-ab','Nifras','Wicket Keeper','Right-hand bat',null,
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/nifras-albrooj.jpg', 'Al-Brooj S.C', 56),
  ('p-faslul-haq','Faslul Haq','All-Rounder','Right-hand bat','Right-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/faslul-haq.jpg', 'Al-Brooj S.C', 57),
  ('p-rifas','Rifas','All-Rounder','Right-hand bat','Right-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/rifas.jpg', 'Al-Ashab S.C', 58),
  ('p-nisardeen','Nisardeen','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/nisardeen.jpg', 'Al-Ashab S.C', 59),
  ('p-sanfas','Sanfas','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/sanfas.jpg', 'Al-Ashab S.C', 60),
  ('p-amsath','Amsath','All-Rounder','Right-hand bat','Left-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/amsath.jpg', 'Al-Ashab S.C', 61),
  ('p-anismeen','Anismeen','All-Rounder','Right-hand bat','Right-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/anismeen.jpg', 'Al-Ashab S.C', 62),
  ('p-selva-kumar','Selva Kumar','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/selva-kumar.jpg', 'United S.C', 63),
  ('p-fairoos-united','Fairoos','All-Rounder','Right-hand bat','Right-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/fairoos-united.jpg', 'United C.C', 64),
  ('p-rafeeulla','Rafeeulla','All-Rounder','Left-hand bat','Left-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/rafeeulla.jpg', 'United C.C', 65),
  ('p-naseem','Naseem','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/naseem.jpg', 'United S.C', 66),
  ('p-ihsan','Ihsan','Wicket Keeper','Right-hand bat',null,
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/ihsan.jpg', 'United C.C', 67),
  ('p-asmeer','Asmeer','All-Rounder','Right-hand bat','Right-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/asmeer.jpg', 'United S.C', 68),
  ('p-musky','Musky','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/musky.jpg', 'United S.C', 69),
  ('p-sajeer','Sajeer','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/sajeer.jpg', 'United S.C', 70),
  ('p-fasan','Fasan','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/fasan.jpg', 'United S.C', 71),
  ('p-aakif','Aakif','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/aakif.jpg', 'United S.C', 72),
  ('p-amjath','Amjath','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/amjath.jpg', 'United S.C', 73),
  ('p-imran-united','Imran','All-Rounder','Right-hand bat','Right-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/imran-united.jpg', 'United S.C', 74),
  ('p-kasjin','Kasjin','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/kasjin.jpg', 'United S.C', 75),
  ('p-rinosh','Rinosh','Bowler','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/rinosh.jpg', 'United S.C', 76),
  ('p-raviyendran','Raviyendran','All-Rounder','Right-hand bat','Right-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/raviyendran.jpg', 'United S.C', 77),
  ('p-aslam','Aslam','Bowler','Right-hand bat','Right-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/aslam.jpg', 'Idimans S.C', 78),
  ('p-ishak','Ishak','All-Rounder','Right-hand bat','Right-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/ishak.jpg', 'Idimans S.C', 79),
  ('p-natheer','Natheer','All-Rounder','Left-hand bat','Left-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/natheer.jpg', 'Idimans S.C', 80),
  ('p-mafas','Mafas','Batsman','Right-hand bat',null,
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/mafas.jpg', 'Idimans S.C', 81),
  ('p-sifan-idimans','Sifan','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/sifan-idimans.jpg', 'Idimans S.C', 82),
  ('p-suhail','Suhail','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/suhail.jpg', 'Idimans S.C', 83),
  ('p-fahir-idimans','Fahir','Bowler','Right-hand bat','Right-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/fahir-idimans.jpg', 'Idimans S.C', 84),
  ('p-saheem','Saheem','Bowler','Right-hand bat','Right-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/saheem.jpg', 'Idimans S.C', 85),
  ('p-arsath','Arsath','Wicket Keeper','Right-hand bat',null,
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/arsath.jpg', 'Idimans S.C', 86),
  ('p-haseen','Haseen','Bowler','Right-hand bat','Right-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/haseen.jpg', 'Melbourne C.C', 87),
  ('p-fazeel','Fazeel','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/fazeel.jpg', 'Melbourne C.C', 88),
  ('p-ijas','Ijas','All-Rounder','Left-hand bat','Left-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/ijas.jpg', 'Melbourne C.C', 89),
  ('p-rifkhan-mcc','Rifkhan','Batsman','Left-hand bat',null,
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/rifkhan-mcc.jpg', 'Melbourne C.C', 90),
  ('p-faisdeen','Faisdeen','All-Rounder','Right-hand bat','Right-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/faisdeen.jpg', 'Melbourne C.C', 91),
  ('p-nafeer','Nafeer','All-Rounder','Right-hand bat','Right-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/nafeer.jpg', 'Melbourne C.C', 92),
  ('p-nifras-mcc','Nifras','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/nifras-mcc.jpg', 'Melbourne C.C', 93),
  ('p-rifkhan-mcc2','Rifkhan','All-Rounder','Left-hand bat','Left-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/rifkhan-mcc2.jpg', 'Melbourne C.C', 94),
  ('p-riyas','Riyas','All-Rounder','Right-hand bat','Right-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/riyas.jpg', 'Melbourne C.C', 95),
  ('p-nowfees','Nowfees','All-Rounder','Right-hand bat','Right-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/nowfees.jpg', 'Genius H.B', 96),
  ('p-rassan','Rassan','All-Rounder','Right-hand bat','Right-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/rassan.jpg', 'Genius H.B', 97),
  ('p-niyas-genius','Niyas','All-Rounder','Left-hand bat','Left-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/niyas-genius.jpg', 'Genius H.B', 98),
  ('p-roshan-genius','Roshan','Batsman','Right-hand bat',null,
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/roshan-genius.jpg', 'Genius H.B', 99),
  ('p-sajath','Sajath','All-Rounder','Right-hand bat','Right-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/sajath.jpg', 'Genius H.B', 100),
  ('p-arsan','Arsan','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/arsan.jpg', 'Genius H.B', 101),
  ('p-atheef','Atheef','Batsman','Right-hand bat',null,
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/atheef.jpg', 'Genius H.B', 102),
  ('p-imran-genius','Imran','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/imran-genius.jpg', 'Genius H.B', 103),
  ('p-vinoth','Vinoth','Wicket Keeper','Left-hand bat',null,
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/vinoth.jpg', 'Genius H.B', 104),
  ('p-fasarath','Fasarath','All-Rounder','Right-hand bat','Right-arm fast medium',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/fasarath.jpg', 'Genius H.B', 105),
  ('p-nafrees','Nafrees','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/nafrees.jpg', 'Genius H.B', 106),
  ('p-aathil-genius','Aathil','All-Rounder','Right-hand bat','Right-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/aathil-genius.jpg', 'Genius H.B', 107),
  ('p-samry','Samry','Wicket Keeper','Right-hand bat',null,
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/samry.jpg', 'Genius H.B', 108),
  ('p-hizam','Hizam','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/hizam.jpg', 'Genius H.B', 109),
  ('p-numaiz','Numaiz','Batsman','Right-hand bat',null,
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/numaiz.jpg', 'Genius H.B', 111),
  ('p-safan','Safan','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/safan.jpg', 'Genius H.B', 112),
  ('p-sathath','Sathath','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/sathath.jpg', 'Genius H.B', 113),
  ('p-raeesul','Raeesul','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/raeesul.jpg', 'Genius H.B', 114),
  ('p-rilwan','Rilwan','All-Rounder','Right-hand bat','Right-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/rilwan.jpg', 'Heaven 11', 115),
  ('p-zaththir','Zaththir','Batsman','Right-hand bat',null,
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/zaththir.jpg', 'Heaven 11', 116),
  ('p-ifkar','Ifkar','Wicket Keeper','Right-hand bat',null,
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/ifkar.jpg', 'Heaven 11', 117),
  ('p-naseem-heaven','Naseem','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/naseem-heaven.jpg', 'Heaven 11', 118),
  ('p-rila','Rila','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/rila.jpg', 'Heaven 11', 119),
  ('p-fasmir','Fasmir','All-Rounder','Left-hand bat','Left-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/fasmir.jpg', 'Heaven 11', 120),
  ('p-ihsham','Ihsham','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/ihsham.jpg', 'Heaven 11', 121),
  ('p-rifthy','Rifthy','All-Rounder','Right-hand bat','Right-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/rifthy.jpg', 'Heaven 11', 122),
  ('p-muyeeth','Muyeeth','All-Rounder','Right-hand bat','Right-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/muyeeth.jpg', 'Heaven 11', 123),
  ('p-nisath','Nisath','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/nisath.jpg', 'Heaven 11', 124),
  ('p-mumthash','Mumthash','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/mumthash.jpg', 'Heaven 11', 125),
  ('p-rifnas','Rifnas','All-Rounder','Right-hand bat','Left-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/rifnas.jpg', 'Heaven 11', 126),
  ('p-hassan','Hassan','All-Rounder','Right-hand bat','Right-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/hassan.jpg', 'Kins National', 127),
  ('p-mishari','Mishari','All-Rounder','Right-hand bat','Right-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/mishari.jpg', 'Kins National', 128),
  ('p-nafeer-kins','Nafeer','All-Rounder','Right-hand bat','Right-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/nafeer-kins.jpg', 'Kins National', 129),
  ('p-warith','Warith','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/warith.jpg', 'Kins National', 130),
  ('p-riskhan','Riskhan','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/riskhan.jpg', 'Kins National', 132),
  ('p-faham','Faham','Bowler','Right-hand bat','Left-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/faham.jpg', 'Kins National', 133),
  ('p-azam','Azam','All-Rounder','Right-hand bat','Right-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/azam.jpg', 'Kins National', 134),
  ('p-faheem','Faheem','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/faheem.jpg', 'Kins National', 135),
  ('p-najath','Najath','All-Rounder','Right-hand bat','Right-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/najath.jpg', 'Kins National', 136),
  ('p-aakil','Aakil','All-Rounder','Right-hand bat','Right-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/aakil.jpg', 'Kins National', 137),
  ('p-fasmir-kins','Fasmir','Bowler','Right-hand bat','Left-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/fasmir-kins.jpg', 'Kins National', 138),
  ('p-iham','Iham','Wicket Keeper','Right-hand bat',null,
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/iham.jpg', 'Kins National', 139),
  ('p-isthikar','Isthikar','All-Rounder','Right-hand bat','Right-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/isthikar.jpg', 'Kins National', 140),
  ('p-musni','Musni','Batsman','Right-hand bat',null,
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/musni.jpg', 'Kins National', 141),
  ('p-nowfan','Nowfan','Batsman','Right-hand bat',null,
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/nowfan.jpg', 'Kins National', 142),
  ('p-faheem-nova','Faheem','Wicket Keeper','Right-hand bat',null,
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/faheem-nova.jpg', 'Nova S.C', 143),
  ('p-yusri','Yusri','Bowler','Right-hand bat','Right-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/yusri.jpg', 'Nova S.C', 144),
  ('p-riswaj','Riswaj','Wicket Keeper','Right-hand bat',null,
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/riswaj.jpg', 'Nova S.C', 145),
  ('p-maasath','Maasath','All-Rounder','Right-hand bat','Right-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/maasath.jpg', 'Nova S.C', 146),
  ('p-sifan-nova','Sifan','All-Rounder','Left-hand bat','Right-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/sifan-nova.jpg', 'Nova S.C', 147),
  ('p-rosan','Rosan','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/rosan.jpg', 'Nova S.C', 148),
  ('p-zahi','Zahi','All-Rounder','Left-hand bat','Left-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/zahi.jpg', 'Nova S.C', 149),
  ('p-krishna','Krishna','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/krishna.jpg', 'Kinniyans S.C', 151),
  ('p-naseer-kinniyans','Naseer','All-Rounder','Right-hand bat','Right-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/naseer-kinniyans.jpg', 'Kinniyans S.C', 152),
  ('p-afri','Afri','All-Rounder','Right-hand bat','Right-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/afri.jpg', 'Kinniyans S.C', 153),
  ('p-sinos','Sinos','All-Rounder','Left-hand bat','Right-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/sinos.jpg', 'Kinniyans S.C', 154),
  ('p-feros-kinniyans','Feros','All-Rounder','Right-hand bat','Right-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/feros-kinniyans.jpg', 'Kinniyans S.C', 156),
  ('p-assal','Assal','All-Rounder','Right-hand bat','Left-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/assal.jpg', 'Kinniyans S.C', 157),
  ('p-nawfal','Nawfal','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/nawfal.jpg', 'Kinniyans S.C', 158),
  ('p-najibullah','Najibullah','Bowler','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/najibullah.jpg', 'Kinniyans S.C', 159),
  ('p-riyas-kinniyans','Riyas','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/riyas-kinniyans.jpg', 'Kinniyans S.C', 160),
  ('p-naheem-kinniyans','Naheem','Wicket Keeper','Right-hand bat',null,
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/naheem-kinniyans.jpg', 'Kinniyans S.C', 161),
  ('p-shafan','Shafan','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/shafan.jpg', 'Kinniyans S.C', 162),
  ('p-mubarak','Mubarak','All-Rounder','Left-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/mubarak.jpg', 'Kinniyans S.C', 163),
  ('p-musarrif','Musarrif','Batsman','Right-hand bat',null,
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/musarrif.jpg', 'Kinniyans S.C', 164),
  ('p-sabith','Sabith','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/sabith.jpg', 'Hero S.C', 165),
  ('p-sanan','Sanan','All-Rounder','Right-hand bat','Right-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/sanan.jpg', 'Hero S.C', 166),
  ('p-aroos','Aroos','All-Rounder','Right-hand bat','Right-arm off spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/aroos.jpg', 'Hero S.C', 167),
  ('p-munas-hero','Munas','All-Rounder','Right-hand bat','Right-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/munas-hero.jpg', 'Hero S.C', 168),
  ('p-nispullah','Nispullah','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/nispullah.jpg', 'Hero S.C', 169),
  ('p-sabran','Sabran','All-Rounder','Right-hand bat','Left-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/sabran.jpg', 'Hero S.C', 170),
  ('p-safran','Safran','Wicket Keeper','Right-hand bat','Right-arm off spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/safran.jpg', 'Hero S.C', 171),
  ('p-riyas-hero','Riyas','All-Rounder','Right-hand bat','Right-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/riyas-hero.jpg', 'Hero S.C', 172),
  ('p-mubarak-hero','Mubarak','Wicket Keeper','Right-hand bat',null,
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/mubarak-hero.jpg', 'Hero S.C', 173),
  ('p-hameed','Hameed','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/hameed.jpg', 'Hero S.C', 174),
  ('p-sawkee','Sawkee','Batsman','Right-hand bat',null,
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/sawkee.jpg', 'Titans C.C', 175),
  ('p-ahnaf','Ahnaf','All-Rounder','Right-hand bat','Right-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/ahnaf.jpg', 'Titans C.C', 176),
  ('p-aakkil','Aakkil','All-Rounder','Left-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/aakkil.jpg', 'Titans C.C', 177),
  ('p-ilahi','Ilahi','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/ilahi.jpg', 'Titans C.C', 178),
  ('p-mufeek','Mufeek','All-Rounder','Right-hand bat','Right-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/mufeek.jpg', 'Titans C.C', 179),
  ('p-afridi','Afridi','All-Rounder','Right-hand bat','Right-arm medium',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/afridi.jpg', 'Titans C.C', 181),
  ('p-musaraf','Musaraf','All-Rounder','Right-hand bat','Right-arm fast medium',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/musaraf.jpg', 'Titans C.C', 182),
  ('p-waseem-khan','Waseem Khan','Wicket Keeper','Right-hand bat',null,
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/waseem-khan.jpg', 'Titans C.C', 183),
  ('p-armas','Armas','Bowler','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/armas.jpg', 'Titans C.C', 185),
  ('p-safan-titans','Safan','Wicket Keeper','Right-hand bat',null,
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/safan-titans.jpg', 'Titans C.C', 186),
  ('p-musaraf-bowler','Musaraf','Bowler','Right-hand bat','Right-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/musaraf-bowler.jpg', 'Titans C.C', 187),
  ('p-rifnas-kinniyans','Rifnas','Batsman','Right-hand bat','Right-arm off spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/rifnas-kinniyans.jpg', 'Kinniyans S.C', 188),
  ('p-usama','Usama','All-Rounder','Right-hand bat','Right-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/usama.jpg', 'Nova S.C', 189),
  ('p-naahir','Naahir','Bowler','Left-hand bat','Left-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/naahir.jpg', 'Kins National', 190),
  ('p-afthah','Afthah','All-Rounder','Right-hand bat','Right-arm medium fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/afthah.jpg', 'Kinniyans S.C', 191),
  ('p-jafeer', 'Jafeer', 'All-Rounder', 'Right-hand bat', 'Right-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/jafeer.jpg', 'Heaven 11', 192),
  ('p-hassan-heaven', 'Hassan', 'Bowler', 'Right-hand bat', 'Right-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/hassan-heaven.jpg', 'Heaven 11', 193),
  ('p-yaseer', 'Yaseer', 'All-Rounder', 'Right-hand bat', 'Right-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/yaseer.jpg', 'Melbourne C.C.', 194),
  ('p-riyath-najah', 'Riyath', 'All-Rounder', 'Right-hand bat', 'Right-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/riyath-najah.jpg', 'AN-NAJAH S.C', 195),
  ('p-razeem', 'Razeem', 'All-Rounder', 'Right-hand bat', 'Right-arm fast',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/razeem.jpg', 'Hameediya S.C', 196),
  ('p-imran-hameediya', 'Imran', 'All-Rounder', 'Right-hand bat', 'Right-arm spin',
   'Base 2,000 LKR', 2000, 'Available For Auction', '/auction/imran-hameediya.jpg', 'Hameediya S.C', 197)
on conflict (id) do update set
  name=excluded.name, role=excluded.role, batting_style=excluded.batting_style,
  bowling_style=excluded.bowling_style, base_price=excluded.base_price,
  base_price_value=excluded.base_price_value, status=excluded.status,
  image=excluded.image, club=excluded.club, sort_order=excluded.sort_order, updated_at=now();
